### ISSUE TITLE
In the log the shot miss, but hit target and deal damage in reality.

### ISSUE THREAD

**Issue by Ronios** [narical/openxcom-accuracy#13]
During a shot, the log shows that the shot miss, but it hits the target and does full damage..

To repeat the bug, you need to throw a flash grenade at a nearby Gillman and the distant Gillman will hit the agent with a reaction attack.

The bug was encountered in version Brutal AI 7.8.1 and 7.10.1.
![screen022](https://github.com/narical/openxcom-accuracy/assets/152795166/e5438d4b-25dc-4b97-8334-1ec3c4cf4d07)
[_miss_in_log_hit_in_real_.zip](https://github.com/narical/openxcom-accuracy/files/13613602/_miss_in_log_hit_in_real_.zip)

**Comment by narical** [comment]
Bug existed due to RA code not aware of arcing trajectories whatsoever. Now arcing shots are removed from under RA calculations (temporary)
