### ISSUE TITLE
In the log the shot hits, but miss in reality.(shoting at the object)

### ISSUE THREAD

**Issue by Ronios** [narical/openxcom-accuracy#17]
When we shoting at the object, not unit, the log shows that the shot hits, but instead flies past the object.

To repeat the bug, you need to select a soldier inside the Raider and throw a throwing star at the lantern opposite the side door.

The bug was encountered on version Brutal AI 9.1.2.  7.12.9.
[Hit_in_log_miss_in_real_object.zip](https://github.com/user-attachments/files/16415367/Hit_in_log_miss_in_real_object.zip)
![screen092](https://github.com/user-attachments/assets/9cdc4773-9bd9-49b0-b2d5-80058eae1556)

**Comment by narical** [comment]
Fixed
